### ISSUE TITLE
Hostname wird nicht übernommen

### ISSUE THREAD

**Issue by GeorgHo** [AWSW-de/WordClock-16x16-LED-matrix-2023#11]
Hallo,
zuerst einmal ein frohes neues Jahr und vielen, vielen Dank für dieses super Projekt und die hervorragende Anleitung.

Ein kleines Problem habe ich, der hinterlegte Hostname in der Code.ino wird nach dem Programmieren des Chips nicht übernommen und es bleibt beim Standard "esp32-898D44.fritz.box".
Ich benutze zum Programmieren die Arduino IDE 2.2.1 und die Includes habe ich alle von den angegebenen Adressen besorg.

Hast du vielleicht einen Tipp woran dies liegen könnte?

Viele Grüße
Georg

**Comment by AWSW-de** [comment]
Hallo,
frohes neues Jahr und vielen Dank für die netten Worte. =)

Das ist ein Thema, an dem ich schon seit über 1 Jahr suche und das Internet ist voll mit ähnlichen Meldungen. Ich habe ESP8266 und ESP32 die den Hostnamen auch in meine Fritz!Box brav übergeben und andere, selbst gleichen Typs weigern sich beharrlich... Bei meinen älteren WordClock ist der Name noch wie eingestellt im Router und bei den neueren nicht mehr... Ich habe irgendwo einen Betrag gelesen, dass ein genereller Bug in den ESP32 sein soll. Es wäre also möglich, dass das per Software irgendwann behoben wird, aber das ist leider Nichts wobei ich Dir helfen kann.

Ich habe daher den Namen in der Fritz!Box manuell noch mal eben für die neueren ESPs eingetragen und scheint zu funktioneren.

Viele Grüße und viel Spaß mit der WordClock =)

**Comment by AWSW-de** [comment]
Hallo,
ich habe heute noch mal danach geschaut und der Bug (wohl im ESP32) ist noch existent...

Was ich beheben konnte ist, dass nun der korrekte, verwendete Hostname sowohl in der Ardurino IDE als auch in der Weboberfläche ausgegeben wird. Dieser Fix und viele weitere neue Funktionen werden in Version >=V3.0.0 enhalten sein. :)

Viele Grüße und ich hoffe, das hilft Dir!

AWSW

**Comment by AWSW-de** [comment]
Hallo,
die neue Version V3.0.0 ist online. Details bei Printables oder hier zu finden: https://youtu.be/-pJWRE3K3IY?si=8FxVR6CvyBasa4BV

**Comment by GeorgHo** [comment]
Hallo,
dies sind ja super Neuigkeiten und was im Video zu sehen ist hast du dir ja wieder super viel Arbeit gemacht (Abo habe ich hinterlassen :-) ).
Derzeit kämpfe ich aber mit dem Sterben der ESP32, ist nun der zweite der den Geist aufgibt und dies (soweit ich es nachvollziehen kann) nachdem ich die Helligkeit über 30 gestellt habe. Dann läuft er einige Zeit, meist fällt zuerst der Webserver aus so, dass man nicht mehr drauf kommt und dann ist dunkel. Beim ersten ESP32 (hier hatte ich auf 50 gestellt) war dann auch kein Programmieren mehr möglich, kam immer Hash Error, der zweite (hier hatte ich auf 35 gestellt) macht eigentlich einen intakten Eindruck, lässt sich sauber Programmieren, aber es kommt auf der Uhr nur WLAN in blau und ein paar sich abwechselnde Anzeigen die ich aber nicht zuordnen kann, aber das WLAN ist nicht zu finden. Als Komponenten habe ich die besorgt, die du vorgeschlagen hat, als ein Netzteil mit 5V 3A und den ESP von AZDelivery.

Hast du einen Tipp woran dies liegen könnte und was ich ändern sollte, dass der nächste ESP nicht stirbt oder wo ich den kaufen sollte? 

Viele Grüße
Georg

**Comment by AWSW-de** [comment]
Hallo Georg.

Dankeschön, ja, das waren 3-4 Tage Arbeit aber nun ist Einiges integriert, was ich eh schon einbauen wollte… 

Wow, das ist ungewöhnlich. Ich frage mich zusätzlich warum einige User so eine hohe Helligkeit brauchen. Bei mir laufen sie maximal auf 22 und bei 50 wäre der Stromverbrauch bestimmt schon fast 3x so hoch… Ich bin mir den 1-2,5W so zufrieden…. Aber um deinem Problem auf den Zahn zu fühlen:

Wenn du das so quasi nachvollziehen kannst, würde ich den ESP32 und die Matrix getrennt an die 5V anschließen:

1. Erst mal Strom trennen. USB Kabel aus dem Netzteil ziehen.  ;-)
2. So 5-10cm vor dem Mikro USB Stecker das USB Kabel durchtrennen. 
3. Die Zuleitung und den nun kurzen Teil vom Mikro USB Kabel an beiden Seiten ca. 3cm isolieren, so dass die 4 Adern sichtbar werden .
4. Du wirst eine rote und schwarze oder rote und weiße Ader finden. Das sind die interessanten. Der Rest kann weg wird nicht benötigt, da für Daten. Wir brauchen nur Strom…
5. Am ESP32 den roten und weißen Draht abklemmen und auch abisolieren.
6. Dann einfach die 3 roten Drähte zusammenlöten für +5V
7. Übrig bleiben die schwarzen und weißen Adern. Das sind die für GND oder Minus/Masse würden wir hier sagen. Die 3 auch zusammen löten. 
als Ergebnis geht nun die USB Zuleitung direkt zur Matrix und der 10cm Mikro USB Stecker geht wieder zur Buchse am ESP32.
8. Unberührt von der ganzen Aktion bleibt der grüne Draht vom ESP32 an IO32 zur Matrix DIN. 
9. Wenn Du alles richtig verlötet und wieder mit IsoBand isoliert hast wird die Matrix nun direkt mit 5V gespießt und der ESP32 über den kleinen USB Stecker und ist Safe.
10. Bitte damit mal eine Zeit lang testen. Sollte somit aber klappen. 

Wenn das nicht zu kompliziert klingt, werde ich die nächste Uhr so beschreiben mit einer kleinen Zeichnung dazu. 

Viel Erfolg =)

**Comment by GeorgHo** [comment]
Hi, nein dies klingt nicht zu kompliziert :-) 
Aber mal sehen ob ich es richtig verstanden habe, Ziel ist es den ESP per USB Stecker mit Strom zu versorgen und nur noch den IO 32 angeschlossen zu haben. Die Matrix wird dann direkt aus dem Kabel und nicht über den ESP mit 5V versorgt.
Damit ist die Gefahr bedingt durch einen zu hohen Strombedarf einen Schaden zu verursachen beseitigt, hört sich super an.

Der zweite ESP ist auch hin, habe mal mit den passenden ESP32 Flash Tools die aktuelle Factory BIN aufgespielt, was auch ging ... aber das WLAN Modul lässt sich nicht mehr zum Arbeiten überzeugen, mal sehen ob ich das Teil ausgetauscht bekomme :-)

Der neue ESP ist schon bestellt und ich berichte in den nächsten Tagen ob die Lösung so funktioniert!!

Vielen Dank für deinen Support
Georg

**Comment by AWSW-de** [comment]
Ja genau. Man könnte auch die Milro USB Buchse ganz weg lassen aber dann muss das Netzteil schon recht gut die 5V abgeben, was das angegebene macht aber dann muss man die richtigen PINs am ESP32 finden. Ohne den Mikro USB Stecker wird der 5V und einer der GND zum Eingang, aber man muss den richtigen GND finden damit der Chip hochläuft. Über den Mikro USB fällt die Suche weg und man hat auch noch den Spannungsregler auf dem Chip um ggf. das. Netzteil auszugleichen. Das dürfte besser sein. 

Das wird so klappen. Ich bin im Prinzip schon an der nächsten Version der Uhr und die wird so verkabelt. Wenn ich es hinbekommen sollte sogar ganz ohne zu löten. =)

 Viele Grüße 🖖

**Comment by GeorgHo** [comment]
Dann gib bitte Info ob es klappt, die ESP's kommen leider erst am Mittwoch, dann schneide ich auch das Kabel auf, vielleicht bist du ja schneller :-)

**Comment by AWSW-de** [comment]
Hi, das funktioniert so. Hab eben an mein 20A Labornetzteil die Schaltung geklemmt wie oben beschrieben. Bei voller Helligkeit (255 anstatt 50) mit allen Farben in weiß, zieht sie fast 16A und der ESP reagiert noch. Also nicht mit dem 3A Netzteil testen… ;-)

**Comment by GeorgHo** [comment]
Hi, neue ESP's sind da und die Verkabelung ist geändert, Kontrast mal auf 35 gestellt .... jetzt heißt es abwarten und schauen was passiert! :-)

**Comment by AWSW-de** [comment]
Hi,

ich drück Daumen. 👍 

Wenn es mit der direkten Anbindung der Matrix an 5V nicht geht, würde mich sehr wundern… Bin seit ein paar Tagen an einer 8x8 LED Pannel LED Uhr dran und die lief auf 100% also 255 als Wert in weiß für einige Stunden gestern Abend. Alles gut, nur dass das weiße PLA Cover 3cm über den LEDs langsam weich wurde… 😂

Danke für die Info und schönen Abend =)

**Comment by GeorgHo** [comment]
Wollte noch eine kurze Rückmeldung geben, Uhr läuft immer noch und dies mit Kontrast auf 40 :-)

**Comment by AWSW-de** [comment]
Fast vergessen zu antworten... Danke fürs Feedback. Denke, diese Anschalung ist eine der nächsten Änderungen... Danke Dir und viel Spaß mit der WordClock =)

**Comment by AWSW-de** [comment]
https://www.printables.com/de/model/768062-wordclock-16x16-2024
https://www.printables.com/de/model/749967-wordclock-16x8-2024

;-)

**Comment by GeorgHo** [comment]
Verdammt, jetzt muss ich noch eine Bauen :-) Werde mal die Teile bestellen!!
Vielen Dank für die ganze Mühe!

**Comment by AWSW-de** [comment]
Hehe =) Bin über dein Feedback gespannt. Gerne bei Printables….

**Comment by GeorgHo** [comment]
Hi, 
bin gerade dabei die Teile zu bestellen, dabei ist mir aufgefallen, dass du für die 2024er Version das ESP32 Typ C NodeMCU Board verwendest. Ich habe hier noch paar ESP32 D1 Mini NodeMCU herum liegen, kann ich das Board auch verwenden oder läuft dann die Software nicht mehr?

**Comment by AWSW-de** [comment]
Hi, schau mal in die FAQ in den Beiträgen. Der D1 Mini ist nicht geeignet. Warum ist in der FAQ erklärt. Der neue ESP32 funktioniert auch deutlich besser. Viele Grüße 🖖
