### ISSUE TITLE
Line:1415 if (update = true)

### ISSUE THREAD

**Issue by racklr** [AWSW-de/WordClock-16x16-LED-matrix-2023#3]
Hello, i think there is a Mistake.

Should something like this: 
if (updatenow == true) {

Bye

**Comment by AWSW-de** [comment]
Hi @racklr,

thanks for the hint. I will correct the typo.

Kind regards.

**Comment by AWSW-de** [comment]
Hi,
V2.1.0 will fix this issue. Thanks for the report!
Kind reagrds

**Comment by racklr** [comment]
Thank you for the great Work. 

Have a good day. 

Bye

Am 8. April 2023 10:00:22 MESZ schrieb AWSW-de ***@***.***>:

**Comment by AWSW-de** [comment]
You too. Thanks =)
