### ISSUE TITLE
Sächsische 

### ISSUE THREAD

**Issue by strato345** [AWSW-de/WordClock-16x16-LED-matrix-2023#4]
Besteht die Möglichkeit eine Matrix in Ostdeutescher Uhrzeit zu erstellen? Soll heißen z.B Dreiviertel Acht für 19:45 bzw. 7:30 oder viertel sieben für 6:15 Uhr

das wäre schön ansonsten super geile Arbeit

**Comment by AWSW-de** [comment]
Hi, 
Danke für die netten Worte =)

Die gleiche Anfrage hatte mir jemand die Tage bei Printables bereits gesendet und ich bräuchte dafür dann die entsprechende Übersetzung der folgenden Liste in GROSSBAUCHSTABEN bitte. Dann sollte das möglich sein, wenn die Texte auf die 16x8 Matrix passen:

`Minutes:
########
0 = EXACTLY
5 = FIVE PAST
10 = TEN PAST
15 = A QUARTER PAST
20 = TWENTY PAST
25 = TWENTYFIVE PAST
30 = HALF PAST
35 = TWENTY FIVE TO
40 = TWENTY TO
45 = A QUARTER TO
50 = TEN TO
55 = FIVE TO

Hours:
######
0 = TWELVE O'CLOCK
1 = ONE O'CLOCK
2 = TWO O'CLOCK
3 = THREE O'CLOCK
4 = FOUR O'CLOCK
5 = FIVE O'CLOCK
6 = SIX O'CLOCK
7 = SEVEN O'CLOCK
8 = EIGHT O'CLOCK
9 = NINE O'CLOCK
10 = TEN O'CLOCK
11 = ELEVEN O'CLOCK

Extra words:
############
WIFI
TIME
RESET
RESTART
UPDATE

A time sentens would look like this:
####################################
IT IS [minutes] [hours] + 1234 MINUTES

+ 1 MINUTE vs. + 2,3,4 MINUTES:
############################
Do you say: + 1 MINUTE and + 2,3,4 MINUTES with the additional S or of course similar in your language?

Please translate these sentenses into your language:
With these i get an understanding how you speak/write the time...
##########################################################
09:00 = It is nine o'clock
09:05 = It is five past nine
09:10 = It is ten past nine
09:15 = It is a quarter past nine
09:20 = It is twenty past nine
09:25 = It is twentyfive past nine
09:30 = It is half past nine
09:35 = It is twentyfive to ten
09:40 = It is twenty to ten
09:45 = It is a quarter to ten
09:50 = It is ten to ten
09:55 = It is five to ten `

**Comment by strato345** [comment]
Ok ich kümmere mich darum

**Comment by RainerHub** [comment]
Hallo,
damit es gleich richtig ist, wäre es vielleicht einfacher, die deutschen Version zu übersetzen. Es sind nur 2 Einträge anders. Ginge das?

Jetzt habe doch ich ein paar Bilder der schwäbischen Version in Betrieb gefunden. Da hätte ich ja Lust auf eine fränkische Version. Kann man die evtl. selber generieren? Die Nachfrage dürfte nicht allzu hoch sein. Die wäre der schwäbische Version ähnlich.

**Comment by franz134** [comment]
Hallo, 
auch wenn schon lange geschlossen, möchte ich helfen (soweit ich kann)
Ich hab mir die Mühe gemacht schon eine "ostdeutsche" Matrix zu erstellen.
Den Code kann bzw. möchte ich aber nicht anpassen, weil ich mich da nicht erst einarbeiten will.

Die ostdeutsche Leseweise nach obigen Schema (als Bsp von um 9 bis um 10): 
0 =  UM 9 oder 9 UHR
5 = FÜNF NACH (UM) 9
10 = ZEHN NACH (UM) 9
15 = VIERTEL 10
20 = ZEHN VOR HALB 10
25 = FÜNF VOR HALB 10
30 = HALB 10
35 = FÜNF NACH HALB 10
40 = ZEHN NACH HALB 10
45 = DREIVIERTEL 10
50 = ZEHN VOR (UM) 10
55 = FÜNF VOR (UM) 10

|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| E | S | R | E | S | E | T | I | S | T | U | P | D | A | T | E |
| F | Ü | N | F | € | D | R | E | I | V | I | E | R | T | E | L |
| Z | E | H | N | X | V | O | R | N | A | C | H | X | U | M |
| H | A | L | B | X | D | R | E | I | N | S | I | E | B | E | N |
| Z | W | E | I | Z | E | H | N | E | U | N | S | E | C | H | S |
| E | L | F | V | I | E | R | Z | W | Ö | L | F | Ü | N | F | / |
| I | A | C | H | T | X | U | H | R | E | S | T | A | R | T | / |
| T | N | + | 1 | 2 | 3 | 4 | X | M | I | N | U | T | E | N | / |

"ZEIT" und "WLAN" konnte ich senkrecht  unten links unterbringen, und die restlichen Extrawörter sind auch enthalten (vermutlich kommen die im Code garnicht mehr zum Einsatz und können ersetzt werden?)
"X" sind Platzhalter die sein müssen, "/" sind sind Auffüller wo auch noch umhergeschoben werden kann (das €-Zeichen kann natürlich auch ersetzt werden) 

Ich fände es klasse, wenn der Idee doch nochmal eine Chance gegeben wird.

**Comment by AWSW-de** [comment]
Hallo, danke für Deine Nachricht. 
Damit sicher gestellt ist, ob das auch wirklich im Ablauf passt, bitte die o.g. Liste übersetzen. Ich hatte sonst schon nach dem Druck, dass irgendwas fehlte und dann wird das echt aufwändig noch was zu ändern: 
https://github.com/AWSW-de/WordClock-16x16-LED-matrix-2023/issues/4#issuecomment-1565654504

Danke Dir.

**Comment by franz134** [comment]
Ich hab dir zu danken, dass du dich dem annimmst
```
Minutes:
########
0 = UM
5 = FÜNF NACH UM
10 = ZEHN NACH UM
15 = VIERTEL
20 = ZEHN VOR HALB
25 = FÜNF VOR HALB
30 = HALB
35 = FÜNF NACH HALB
40 = ZEHN NACH HALB
45 = DREIVIERTEL
50 = ZEHN VOR UM
55 = FÜNF VOR UM

Hours:
######
0 = ZWÖLF
1 = EINS
2 = ZWEI
3 = DREI
4 = VIER
5 = FÜNF
6 = SECHS
7 = SIEBEN
8 = ACHT
9 = NEUN
10 = ZEHN
11 = ELF

Extra words:
############
WLAN (vertikal)
ZEIT (vertikal)
RESET
RESTART
UPDATE

A time sentens would look like this:
####################################
ES IST [minutes] [hours*] + 1234 MINUTEN

+ 1 MINUTE vs. + 2,3,4 MINUTEN:
############################
Do you say: + 1 MINUTE and + 2,3,4 MINUTEN with the additional N or of course similar in your language?

Please translate these sentenses into your language:
With these i get an understanding how you speak/write the time...
##########################################################
09:00 = Es ist um neun
09:05 = Es ist fünf nach um neun
09:10 = Es ist zehn nach um neun
09:15 = Es ist viertel zehn
09:20 = Es ist zehn vor halb zehn
09:25 = Es ist fünf vor halb zehn
09:30 = Es ist halb zehn
09:35 = Es ist fünf nach halb zehn
09:40 = Es ist zehn nach halb zehn
09:45 = Es ist dreiviertel zehn
09:50 = Es ist zehn vor um zehn
09:55 = Es ist fünf vor um zehn
```
*Achtung, bei den Stunden wird sich beginnend mit "viertel" (nicht halb wie in anderen Sprachen) auf die nächste volle Stunde bezogen 

Mit meiner erstellten Matrix bestünde theoretisch auch die Möglichkeit die Sätze umzuformulieren indem man "um" weglässt und "Uhr" hinzufügt, also: "Es ist neun Uhr" (wird aber in Realität kaum so gesagt und erinnert mich eher an tagesschau)

**Comment by franz134** [comment]
Da hat mich der Ehrgeiz doch gepackt.. hier der Code mit meiner neuen Variante nach obiger Matrix.
Keine Garantie auf Fehlerfreiheit, ich kanns noch nicht testen, da meine LED Matrix noch nicht angekommen sind.

[Code.zip](https://github.com/AWSW-de/WordClock-16x16-LED-matrix-2023/files/13943221/Code.zip)

Kannst du evtl die 3d datei der Front als .step (oder noch lieber .f3z wenn in Fusion erstellt) teilen?
Du kannst den Thread ja auch erstmal wieder öffnen

**Comment by AWSW-de** [comment]
Hallo,
danke, schau ich mal rein. Die Model-Dateien werde ich allerdings nicht veröffentlichen. Damit hab ich echt negative Erfahrungen gemacht...

**Comment by strato345** [comment]
wie geil :)

**Comment by strato345** [comment]
hab nie die zeit gefunden

**Comment by AWSW-de** [comment]
Software V3.4.0 und Layout in 2023er Modellen V1-V3 sind verfügbar. Viel Spaß damit! 

PS: Ich habe es nicht gedruckt, aber das Layout mehrfach kontrolliert. Ich denke, ihr werdet das für Euch testen können, ob es so passt. ;-)

**Comment by franz134** [comment]
Schade, dass meine Matrix mit den versteckten Extrawörter nicht gut genug  war, zumal ich ja sogar den passenden Code mitgeliefert hab, trotzdem danke, ich werd's ausprobieren.

**Comment by AWSW-de** [comment]
Das konnte ich so nicht umsetzen. Das würde in der Zukunft schlechter wartbar werden, wenn mehr Sprachen dazu kommen…

**Comment by franz134** [comment]
![IMG_20240124_124722~2](https://github.com/AWSW-de/WordClock-16x16-LED-matrix-2023/assets/98423516/032f8ff4-06b9-461d-ba7c-1c540bcd3ac0)

Funktioniert problemlos 👍🏼

**Comment by AWSW-de** [comment]
Super! Danke fürs Feedback und viel Spaß damit =)
