### ISSUE TITLE
Led issue with italian language

### ISSUE THREAD

**Issue by tatobrutto** [AWSW-de/WordClock-16x16-LED-matrix-2023#5]
Hi,
when language is set to italian and hour is between 01:00-01:59 or between 13:00-13:59 the clock shows "SONO LE" and "E'" but the leds for "SONO LE" should be powered off. So it comes like "SONO LE E' L'UNA" (wrong) instead of simply "E' L'UNA" (correct).
Thanks for this awesome project.

Probably is enough to move the block with "SONO LE" after the xHour calculation and add an "if" in order to execute only when hour is >1 
```
===============================================
if (langLEDlayout == 4) {  // IT:

    //set hour from 1 to 12 (at noon, or midnight)
    int xHour = (iHour % 12);
    if (xHour == 0)
      xHour = 12;
    // at minute 40 hour needs to be counted up:
    if (iMinute >= 40) {
      if (xHour == 12)
        xHour = 1;
      else
        xHour++;
    }

    if (xHour > 1) {
      // SONO LE:
      setLEDcol(9, 10, colorRGB);   // LE
      setLEDcol(21, 22, colorRGB);  // 2nd row
      setLEDcol(12, 15, colorRGB);  // SONO
      setLEDcol(16, 19, colorRGB);  // 2nd row
      if (testPrintTimeTexts == 1) {
        Serial.println("");
        Serial.print(hours);
        Serial.print(":");
        Serial.print(minutes);
        Serial.print(" --> SONO LE ");
      }
    }

.......
===============================================
```
Tato

**Comment by AWSW-de** [comment]
Hello Tato,
Thanks for the hint and the nice words. I will change this. 

Kind regards =)

**Comment by AWSW-de** [comment]
Hello Tato,
V2.6.3 will fix this issue. Have fun and many thanks for the report. =)

Kind regards AWSW
