### ISSUE TITLE
RTC Modul Support

### ISSUE THREAD

**Issue by WaldperlachFabi** [AWSW-de/WordClock-16x16-LED-matrix-2023#7]
Ich würde es cool finden, wenn man die zeit nur ein mal einstellen müsste und dazu eine WLAN Verbindung bräuchte und dann nie wieder, das könnte man bspw mit einem RTC Modul realisieren.

**Comment by AWSW-de** [comment]
Hi,
Danke für Deinen Beitrag. Bei der Erstellung der 2023er WordClocks habe ich mir das auch überlegt aber das macht aus meiner Sicht nur bedingt Sinn aus 2 Gründen:

- Du könntest dann die Uhr nicht mehr in ihren Farben, etc. oder mit den smarten Funktionen steuern über die Web Links. Man würde also die komplette Konfiguration der WordClock verlieren. 
- Der 2. Grund ist, dass ich mit der 1. WordClock aus 2022 mit RTF sehr viele Anfragen mit Problemen von Usern erhalten habe, so dass ich die RTCs mittlerweile nicht mehr wirklich mag. Sie haben auch andere Nachteile.

Ich habe aber eine Lösung auf Software Basis, die Du Dir bitte mal anschauen solltest. Oben in dieser Seite zur smarten WordClock 2023 findest Du den sogenannten „Online“ und „Offline“ Modus. Das würde ich zur Lösung beider Punkte anbieten und man muss bis man die Uhr vom Strom trennt oder neu startet auch nicht mehr neu stellen:
https://www.printables.com/de/model/331012-wordclock-16x16-led-matrix

Würde ich für eine bessere Lösung halten und viele User würden das sehr einfach zu verdrahtende Projekt weiter erstellen wollen. Jeder Baustein mehr ist für viele eine echte Hürde…

Viele Grüße 🖖

**Comment by AWSW-de** [comment]
Gerne.
Die Varianten sind nicht kompatibel. Müsste ich entsprechend in diese Variante transferieren. 
Würde Dir die Lösung entsprechend ausreichen? Die WordClock wäre dann ja auch nicht komplett offline weil sie intern noch den Zugang bereitstellt…

**Comment by WaldperlachFabi** [comment]
Passt, so ich benutzte aber erstmal noch die Version 2023-V3.
Wenn ich Flashe und dann in den seriellen Monitor gucke kriege ich das und er bootet nicht:
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13260
load:0x40080400,len:3028
entry 0x400805e4
######################################################################
# WordClock startup of version: V2.6.4
######################################################################

abort() was called at PC 0x400853cb on core 1


Backtrace: 0x40083d45:0x3ffb20a0 0x4008d965:0x3ffb20c0 0x40092e29:0x3ffb20e0 0x400853cb:0x3ffb2160 0x40085515:0x3ffb2190 0x400f2f6c:0x3ffb21b0 0x400e1986:0x3ffb21f0 0x400e1b65:0x3ffb2240 0x400dbdf4:0x3ffb2260 0x400f0e06:0x3ffb2290

**Comment by AWSW-de** [comment]
Bitte die angegebenen Komponenten verwenden. Das Verhalten kann aber auch auf zu schlechte Stromversorgung hindeuten. Verwende bitte mal ein kürzeres, gutes USB Kabel.

**Comment by WaldperlachFabi** [comment]
Ich probiere jetzt erstmal die Version hier zum laufen zu bringen:)
Hardware: 
https://a.aliexpress.com/_mMe7jOG (2104-Variante) und das 16x16 Matrix.
Flashen hat alles geklappt ohne error etc.
Auch beim Versuch mit einem 5cm Kabel an einem 5V 3A Netzteil hat es nicht geklappt und er ist nicht gebootet.
Liegt das an dem ESP32?
Mit freundlichen Grüßen
Fabi

**Comment by AWSW-de** [comment]
Kann gut sein. Es gibt viele Clone die vermeintlich billiger sind aber nichts taugen…

**Comment by AWSW-de** [comment]
Ich habe es gerade noch mal komplett neu runter geladen und meine lokal gespeicherten Libraries komplett gelöscht und auch den Code der WordClock neu geladen plus genau diese angegebenen Libraries:

// # - Adafruit NeoPixel      // by Adafruit:                     https://github.com/adafruit/Adafruit_NeoPixel
// # - AsyncTCP               // by me-no-dev:                    https://github.com/me-no-dev/AsyncTCP
// # - ESPAsyncWebServer      // by me-no-dev:                    https://github.com/me-no-dev/ESPAsyncWebServer
// # - ESPUI                  // by s00500:                       https://github.com/s00500/ESPUI/archive/refs/tags/2.2.3.zip
// # - ArduinoJson            // by bblanchon:                    https://github.com/bblanchon/ArduinoJson
// # - LITTLEFS               // by lorol:                        https://github.com/lorol/LITTLEFS

Damit kompiliert es und eine neue WordClock arbeitet damit anschließend.

Konrtolliere bitte noch mal genau die Schritte und insbesondere die Libraries. Dann muss es funktionieren.

Vielleicht liefert Dein USB Port vom Rechner auch einfach zu wenig Strom oder das USB Kabel ist zu lage. Das macht viel aus...

Viel Erfolg :)

**Comment by WaldperlachFabi** [comment]
Hab’s geschafft - ich hab einfach genau das gleiche was ich schon mal gemacht hatte auf nem anderen Pc nochmal gemacht und den ESP dann nochmal neu geflashed.
Jetzt ging es!
Vielen Dank!
Fabi

**Comment by AWSW-de** [comment]
Super! Viel Spaß damit =)
